# Generated by Django 5.0 on 2024-11-04 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('janr', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='static/images')),
                ('film', models.FileField(upload_to='static/videos')),
                ('treiler', models.FileField(upload_to='static/videos')),
            ],
        ),
        migrations.CreateModel(
            name='Theatr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('vip', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.film')),
                ('theatr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.theatr')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('online', 'cash')], default='pending', max_length=50)),
                ('online_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.onlineshop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.user')),
            ],
        ),
    ]
